// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_pkg_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsSuspended   bool                   `protobuf:"varint,4,opt,name=is_suspended,json=isSuspended,proto3" json:"is_suspended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_pkg_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyTokenResponse) GetIsSuspended() bool {
	if x != nil {
		return x.IsSuspended
	}
	return false
}

var File_pkg_proto_auth_auth_proto protoreflect.FileDescriptor

const file_pkg_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/auth/auth.proto\x12\x04auth\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"r\n" +
	"\x13VerifyTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fis_suspended\x18\x04 \x01(\bR\visSuspended2Q\n" +
	"\vAuthService\x12B\n" +
	"\vVerifyToken\x12\x18.auth.VerifyTokenRequest\x1a\x19.auth.VerifyTokenResponseB Z\x1ego-audio-stream/pkg/proto/authb\x06proto3"

var (
	file_pkg_proto_auth_auth_proto_rawDescOnce sync.Once
	file_pkg_proto_auth_auth_proto_rawDescData []byte
)

func file_pkg_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_pkg_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_pkg_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_auth_proto_rawDesc), len(file_pkg_proto_auth_auth_proto_rawDesc)))
	})
	return file_pkg_proto_auth_auth_proto_rawDescData
}

var file_pkg_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_auth_auth_proto_goTypes = []any{
	(*VerifyTokenRequest)(nil),  // 0: auth.VerifyTokenRequest
	(*VerifyTokenResponse)(nil), // 1: auth.VerifyTokenResponse
}
var file_pkg_proto_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.VerifyToken:input_type -> auth.VerifyTokenRequest
	1, // 1: auth.AuthService.VerifyToken:output_type -> auth.VerifyTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_auth_auth_proto_init() }
func file_pkg_proto_auth_auth_proto_init() {
	if File_pkg_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_auth_proto_rawDesc), len(file_pkg_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_pkg_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_pkg_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_pkg_proto_auth_auth_proto = out.File
	file_pkg_proto_auth_auth_proto_goTypes = nil
	file_pkg_proto_auth_auth_proto_depIdxs = nil
}
